import type { Metadata } from "next";
import { cookies } from "next/headers";
import localFont from "next/font/local";
import ThemeProvider from "@/app/providers/ThemeProvider";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { THEME } from "@/app/constants";
import { Theme } from "./types";
import styles from "./layout.module.css";
import "./globals.css";

const plusJakartaSans = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--font-plus-jakarta-sans",
});
const spaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk-Regular.ttf",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Rated-fe",
  description: "Generated by Jaden Lu",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = (cookieStore.get("theme")?.value ?? THEME) as Theme;

  return (
    <html lang="en" data-theme={theme}>
      <body className={`${plusJakartaSans.variable} ${spaceGrotesk.variable}`}>
        <div className={styles.app}>
          <ThemeProvider theme={theme}>
            <Navbar />
            <div className={styles.page}>{children}</div>
            <Footer />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
